{{- if and .Values.persistence.enabled (not .Values.persistence.cftData.existingClaim) -}}
{{- if and .Values.persistence.cftData.nfsPath .Values.persistence.cftData.nfsServer -}}
kind: PersistentVolume
apiVersion: v1
metadata:
  name: {{ include "transfer-cft.fullname" . }}-nfs-volume
  labels:
    {{- include "transfer-cft.labels" . | nindent 4 }}
    {{- if .Values.podLabels }}
    {{- toYaml .Values.podLabels | nindent 4 }}
    {{- end }}
spec:
  accessModes:
    - {{ .Values.persistence.cftData.accessMode }}
  capacity:
    storage: {{ .Values.persistence.cftData.size}}
  nfs:
    server: {{ .Values.persistence.cftData.nfsServer | quote }}
    path: {{ .Values.persistence.cftData.nfsPath | quote }}
{{- if .Values.persistence.cftData.storageClass }}
  {{- if (eq "-" .Values.persistence.cftData.storageClass) }}
  storageClassName: ""
  {{- else }}
  storageClassName: {{ .Values.persistence.cftData.storageClass }}
  {{- end }}
{{- else }}
  storageClassName: {{ include "transfer-cft.fullname" . }}-nfs
{{- end }}
{{- if .Values.persistence.cftData.reclaimPolicy }}
  persistentVolumeReclaimPolicy: {{ .Values.persistence.cftData.reclaimPolicy | quote }}
{{- end }}
{{- if .Values.persistence.cftData.mountOptions }}
  {{- with .Values.persistence.cftData.mountOptions }}
  mountOptions:
    {{ toYaml . }}
  {{- end }}
{{- end }}
{{- end }}
{{- end -}}
